[project]
name = "blackJack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pygame>=2.6.1",
]

[tool.setuptools]
packages = ["blackJack"]
